[package]
name = "rperf"
version = "0.0.1"
description = "iperf, but meant for real-world conditions and analytics"
authors = ["Neil Tallim <neiltallim@3d-p.com>"]
edition = "2018"
repository = "https://gitlab.3d-p.com/neiltallim/rperf"
license = "<undefined>"
keywords = ["network", "performance", "tcp", "udp", "sctp"]
categories = ["network-utilities"]
readme = "README.md"

[dependencies]
chashmap = "2.2"
chrono = "0.4"
clap = "~2.33.3"
core_affinity = "0.5"
ctrlc = "3.1"
env_logger = "0.8"
lazy_static = "1.4"
libc = "0.2"
log = {version = "0.4", features = ["std"]}
mio = "0.6"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
simple-error = "0.2"
uuid = {version = "0.8", features = ["v4"]}
